### ISSUE TITLE
Loading Icon and Improvements

### ISSUE THREAD

**Issue by huanjue** [domkalan/yh-BootPanel#1]
This is a very exciting work, but I think the loading icon in the sub page is not easy to be found.Because it is very small, and it is located on the right top of the page,and overlapping colors..
You should make a bigger one.In the middle of the page.
There are some other suggestions, I hope you can accept that they will be put forward in the future.
Thank you.

**Comment by domkalan** [comment]
What loading icon are we talking about exactly. Can you provide a screenshot so it can give me a better understanding?

**Comment by huanjue** [comment]
I'm sorry, I can't provide, and it like hostinger's loading icon, in the middle of the page,and it is big..

**Comment by domkalan** [comment]
Ah I think I get what you are aiming at. Are you talking about something like [this](http://joaopereirawd.github.io/fakeLoader.js/demo/demo4.html)?

**Comment by huanjue** [comment]
Yes, your understanding is excellent.I hope it can be added to the bootpanel1.4.

**Comment by domkalan** [comment]
Yes, as a matter of fact I was working on it a few days ago. If it is stable you should see it added as the next major version.
